---
- name: Download openscap source code
  get_url: url=https://github.com/OpenSCAP/openscap/releases/download/1.2.5/openscap-1.2.5.tar.gz dest=/tmp/openscap-1.2.5.tar.gz

- name: Unzip openscap source code
  shell: 'cd /tmp; tar zxvf openscap-1.2.5.tar.gz'

# Install required components
- name: install git
  yum: name=git state=latest

- name: install gcc
  yum: name=gcc state=latest

- name: install autoconf
  yum: name=autoconf state=latest

- name: install automake
  yum: name=automake state=latest

- name: install libtool
  yum: name=libtool state=latest

- name: install libcurl-devel
  yum: name=libcurl-devel state=latest

- name: install libxml2-devel
  yum: name=libxml2-devel state=latest

- name: install libxslt-devel
  yum: name=libxslt-devel state=latest

- name: install pcre-devel
  yum: name=pcre-devel state=latest

- name: install swig
  yum: name=swig state=latest

- name: install python-devel
  yum: name=python-devel state=latest

- name: build and install openscap
  shell: 'cd /tmp/openscap-1.2.5; ./configure && make && make install'

- name: install openscap-utils
  yum: name=openscap-utils state=latest

- name: clone and build scap-security guide
  shell: 'git clone https://github.com/OpenSCAP/scap-security-guide.git && cd scap-security-guide && make SSG_VERSION_IS_GIT_SNAPSHOT=no rpm && rpm -i rpmbuild/RPMS/noarch/scap-security-guide-0.1.25-1.el7.centos.noarch.rpm' 

